#
# Copyright (C) 2012 Samsung Electronics
# R. Chandrasekar <rcsekar@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SOUND)	+= sound.o
obj-$(CONFIG_I2S)	+= sound-i2s.o
obj-$(CONFIG_I2S_SAMSUNG)	+= samsung-i2s.o
obj-$(CONFIG_SOUND_SANDBOX)	+= sandbox.o
obj-$(CONFIG_SOUND_WM8994)	+= wm8994.o
obj-$(CONFIG_SOUND_MAX98095)	+= max98095.o
obj-$(CONFIG_SUN3I_SOUND)	+= sun3i-sound.o
obj-$(CONFIG_SUNXI_SOUND)       += sunxi_rw_func.o
obj-$(CONFIG_SUN8IW8_SOUND)	+= sun8iw8-codec.o
obj-$(CONFIG_SUN8IW15_SOUND)	+= sun8iw15-codec.o
obj-$(CONFIG_SUNXI_BOOT_TONE)	+= sunxi_boot_tone.o
