#
# (C) Copyright 2000-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
#  (C) Copyright 2013
#  Bo Shen <voice.shen@atmel.com>
#
#  SPDX-License-Identifier:	GPL-2.0+
#




obj-y	+= clock.o
obj-y	+= board.o
obj-y	+= usb_clock.o
obj-y	+= key_clock.o

